pipeline {
  agent none
  stages{
      stage("build"){
        when{
            changeset "**/vote/**"
          }

        agent {
          docker {
            image 'python:2.7.16-slim'
            args '--user root'         
          }
        }
        steps{
          echo 'Compiling vote app..'
          dir('vote'){
            sh 'pip install -r requirements.txt'
          }
        }
      }
      stage("test"){
        when{
          changeset "**/vote/**"
        }
        agent {
          docker {
            image 'python:2.7.16-slim'
            args '--user root'
          }
        }
        steps{
          echo 'Running Unit Tets on vote app..'
          dir('vote'){
            sh 'pip install -r requirements.txt'
            sh 'nosetests -v'
           }

          }
      }
  }

  post{
    always{
        echo 'Building multibranch pipeline for vote is completed..'
    }
  }
}